### ISSUE TITLE
BungeeAuth & Snap : There are no available servers

### ISSUE THREAD

**Issue by DoctaEnkoda** [Phoenix616/Snap#7]
#### Used Version
Latest (15/03)
 
 
#### Config

 ```yaml
# BungeeAuth Config File

Use SQLite: true
# Set this to true if you want to use a file based database (SQLite) rather than MySQL

Host: 127.0.0.1
# Please enter the Host of your MySQL database here.

Port: 3306
# Please enter the port where your MySQL database is hosted.

Username: 'root'
# The Username which should be used to login to the MySQL database.

Password: ''
# The Password which should be used to login to the MySQL database. If you don't have a password, please leave two single quotation marks (') in this field.

DBName: Bungee
#The name of the MySQL database where BungeeAuth's Tables shall be created.

Lobby: lobby
# The name of the lobby server.

Fallback Lobby: lobby
# The name of the fallback lobby server in case the main lobby is down.

AuthLobby: lobby
# The name of the lobby where players are pushed before they authenticate. leave it same as normal lobby if you don't have an auth lobby.

Fallback AuthLobby: lobby
# The name of the fallback AuthLobby server in case the main AuthLobby is down.

Ask Email: false
# Set this to True if you want the plugin to prompt users to register their email when they login to the server for the first time.

Session Length: 5
# How long (in minutes) does the user's session remains running after a player quits. This allows the user to log back in within the time frame without
# having to type their password again. If user logs in from a different IP, they will be asked to type their password again for security reasons.

Guest Session Length: 60
# How long (in seconds) the user has before they have to register or login. Set this to 0 to disable guest session time limits.

Legal Usernames Characters: "[a-zA-Z0-9_]*"
# Allowed Characters in Usernames (). Enclose in quotation marks.

Users per IP: 5
# Number of users that can register (not login) from the same IP.

Password Tries: 5
# Number of times a player can input a wrong password before getting their account locked. Set this to 0 to disable this feature.

Wrong Password Timeout: 5
# Timeout (in minutes) for players who spam commands. The timeout occurs if a player tries to use a BungeeAuth command more than 10 times. Set this to 0 to disable this feature.

Guest Server Failsafe Check: true
# A failsafe method that runs every 10 seconds to check if a guest player is in AuthLobby, and if not, moves them to AuthLobby.

#---------------------------- PHP API AREA ----------------------------#

Enable PHP API: false
# Enabling this will make the plugin listen to API requests from a port.

PHP API Port: 1395
# The port that the plugin will be listening for API requests on.

API Password: 'aaaa'
# The password required in the API requests for a response. If you don't have a password, please leave two single quotation marks (') in this field.

API Error Limit: 5
# Set the maximum number of wrong api password attempts used by a php script before it's ip gets blocked. IP will be blocked until removed from apiblacklist.txt
 ```
 
#### Full Log
Just : 
``` 
[connected player] DoctaEnkoda (/10.8.0.200:52200) has disconnected: There are no available servers.
[14:01:56 INFO]: [server connection] DoctaEnkoda -> lobby has disconnected
```

#### What other programs/plugins are you running?
https://github.com/vik1395/BungeeAuth-Minecraft

#### What is happening?
Impossible to connect any server 'lobby'
